version: '3.7'
services:
  web:
    build: ./nodejinxer-nginx
    ports:
      - "8080:80"
  node1:
    depends_on:
      - web
    build: ./nodejinxer-nodejs
    restart: always
    ports:
      - "3001:3000"
  node2:
    depends_on:
      - web
    build: ./nodejinxer-nodejs
    restart: always
    ports:
      - "3002:3000"
  node3:
    depends_on:
      - web
    build: ./nodejinxer-nodejs
    restart: always
    ports:
      - "3003:3000"