version: '3'
services:
  node1:
    build: ./nodejinxer-nodejs
    restart: always
  node2:
    build: ./nodejinxer-nodejs
    restart: always
  node3:
    build: ./nodejinxer-nodejs
    restart: always
  web:
    depends_on:
      - node1
      - node2
      - node3
    build: ./nodejinxer-nginx
    ports:
      - "8080:80"