version: '3'
services:
  node1:
    image: zireael/basic-node
    restart: always
  node2:
    image: zireael/basic-node
    restart: always
  node3:
    image: zireael/basic-node
    restart: always
  web:
    depends_on:
      - node1
      - node2
      - node3
    image: zireael/nginx-balanced
    ports:
      - "8080:80"